### ISSUE TITLE
Security contact?

### ISSUE THREAD

**Issue by mogulano** [ONSdigital/ras-frontstage#643]
How could I report a security vulnerability?

**Comment by jterryons** [comment]
Hello, Thank you for contacting us.
Our vulnerability reporting information page is [here](https://surveys.ons.gov.uk/help/vulnerability-reporting). That will give you some information on how to report it. That should direct you to [hackerone](https://hackerone.com/52fa7bc0-5356-4c86-9f79-eeb03e1d55cc/embedded_submissions/new) for reporting security issues.

**Comment by mogulano** [comment]
Thank you for the reply.
Is there an email like security@ons.gov.uk to report to? A requirement to accept hackerone policies creates an unnecessary barrier to report vulnerabilities. You are free then to copy the report to hackerone for tracking.

**Comment by mfcrocker** [comment]
Fixed in #644
